### ISSUE TITLE
Totally Unstable playback

### ISSUE THREAD

**Issue by sirjohndfox** [ahlstromcj/seq66#101]
Just compiled seq66 can't get steady playback. Not sure if it's my system, new to manjaro and might have done a dubious up-date.  But it hangs often and then releases a whole bunch of notes... 
Tried with yoshimi too. same thing... Is my system broken?
https://youtu.be/v6H4LGk8Kyc

**Comment by ahlstromcj** [comment]
Check your JACK settings.  If the "Period" is large (e.g 2048, 4096, etc.)
there is a known issue with the "rtmidi" code.  You can change the period in
QJackCtl.  You can also view the current JACK settings (requires jackdbus):

     $ jack_control dp

and look at the line "period: Frames per period (uint:set:1024:2048)" and note
that the second number is the current setting.  I have it set high at present
in order to work on sticky issue #100.

If set high, try setting it to 128.  It will still be slightly raggy but
generally not noticeable.

Thanks for the video, very helpful to see.

-------- sirjohndfox 05:31 Tue 11 Oct      --------

>https://youtu.be/v6H4LGk8Kyc

**Comment by sirjohndfox** [comment]
Further investigation leads me to believe it might be something with the realtime kernel and video drivers! bloody annoying!  I wonder where to start looking...

**Comment by sirjohndfox** [comment]
As regards the frames, I went down from 128 to 64 no difference.

**Comment by ahlstromcj** [comment]
One thing I have noted, is that a real-time kernel is not needed for JACK these
days.  Still, not sure why that could cause an issue.

-------- sirjohndfox 06:14 Tue 11 Oct      --------

>As regards the frames, I went down from 128 to 64 no difference.

**Comment by sirjohndfox** [comment]
I've identified some flaws in the configuration of my system overall. I'll fix them and see if the error persists. Feel free to close the issues. Sorry if it was irrelevant.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ahlstromcj** [comment]
Whatever you find out, let us know here.  It could be very useful to include in
the documentation.  Thanks!

**Comment by ahlstromcj** [comment]
Closing.  If still an issue, make a new report and make me earn my keep!
