### ISSUE TITLE
Can't increase clip length while transport is running

### ISSUE THREAD

**Issue by mathiasfriman** [ahlstromcj/seq66#107]
Hi, long time no see.

First of all, thank you for this great software, I'm using it constantly. 

I have recently tried to "upgrade" to Seq66 and I am primarily using it as a midi looper, but when outlining new songs I live record the input. What has worked in previous versions like seq24 and Sequencer64 (at least the version I have) no longer works. 

I cannot increase clip/pattern length while I play the song, even if the clip/pattern itself is not playing. [Here is a video of it](https://www.youtube.com/watch?v=fvACGI-FUSs). Is there a setting I'm unaware of that I need to change, or some other workaroud that I'm unfamiliar with?

Also, if there is some keyboard shortcut or something to arm a track for recording without using the mouse, I would be very grateful.

Thanks!

**Comment by ahlstromcj** [comment]
I will look at the symptom in your video.  It seems to be okay with ALSA but I
need to check JACK as well.

One thing you can do to increase length as you record is open the pattern
editor for the track you want to fill.  Where the drop-down says "Merge",
select "Expand" instead.  That will automatically expand the pattern the whole
time recording is on (whether or not notes are being recorded, if I remember
correctly.

I will have to review how the recording setup works again, and might need to
add another command to toggle recording.  Gotta check because sometimes I
forget what I've already coded :-D.

The "=" and "-" keys open a pattern for editing in the pattern editor and the
event editor respectively. (Example, "=1" will open pattern 0, "=1c" will open
pattern 11.  I may need to add a similar key to toggle recording for a pattern.

Will try to get a resolution by the weekend.  Thanks, much appreciated!

**Comment by mathiasfriman** [comment]
Oh, thanks for reminding me about that! I've tried recording using "Expand", and it failed in a spectacular way.

Lets say I have Jack transport running for a while, so that the transport indicator (or whatever it is called) says for instance 096:X:xxx. I've had it running like that up to 800 or something and the same happens:

When arming a pattern for recording using "Expand", the pattern becomes as long as the number (96 bars in this case) where I press down the keys on my keyboard. 

It then loops being 96 bars, until I press down a couple other keys, where it again expands to whatever the transport indicates at that point (for example 142:X:xxx). 

When no more keys are being pressed, the pattern becomes 142 bars long, until I press some more keys.

And it seems to repeat like that until I press the Stop button, when it starts over on 001:X:xxx. The pattern length remains the same though.

**Comment by ahlstromcj** [comment]
Okay, it looks like I have some more investigation to do.  I did verify that
the pattern length change due to the menu entry won't change when JACK
transport is enabled (even if ALSA is used for the MIDI).

**Comment by ahlstromcj** [comment]
Fixed issues with the grid mode button on the main window (the one that says "Loop").  Change it to "RECORD", and toggling a pattern will toggle recording.  By default, Shift-F2 will change it to "RECORD" mode, and Shift-F1 goes back to "Loop" (normal arming/muting) mode.  There are other modes that one can select in the drop-down (e.g. to Delete a pattern or Clear its events, and Double to double the number of measures in the pattern.)  The potential issue with keystrokes is changing the focus of the keystrokes so that they don't appear to act on a grid button.  MIDI control should work.  Skim the 'ctrl' file to see the default keystrokes.  I still have a bit more work to do. The fixes so far are in the "portfix" branch.

**Comment by mathiasfriman** [comment]
Both toggling "Record" and "Loop" using Shift-F2 and Shift-F1 respectively works nicely in the "portfix" branch. It also works to change length of the pattern in the "Editor" tab. Have yet to try the ctrl file with my Launchpad Pro Mk 1.

Thanks a lot for all your hard work!

**Comment by mathiasfriman** [comment]
Forgot about this issue, which seems to be merged into the main branch now. Both recording and Looping works, as well as increasing and decreasing length of a pattern in the Editor tab. Awesome, I'm closing this one!
