### ISSUE TITLE
Option to close pattern windows with esc key? 

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#117]
Being able to close pattern windows with just a press of the esc key would make working within seq66 quite a bit easier IMO.

**Comment by ahlstromcj** [comment]
Well, the pattern window isn't really a dialog box. Window managers (even
Windows) offer keystrokes to close windows. I configure both Fluxbox and
Xfce4 to use Super-X. Plus Esc is already devoted to stopping playback or
getting out of paint mode. Could devote the Windows key Alt-F4 to that
purpose. Or Shift or Ctrl-Esc. Need to think about it...

**Comment by mxmilkiib** [comment]
I guess I imagine it as being like a dialog box, or, at least, I imagine it as being a window I would like to close as quickly as a dialog box (given the number of times one has to open and close pattern windows throughout one's use of seq66).

**Comment by ahlstromcj** [comment]
As you see, I added a 'usr' option to enable this feature, which is not set by default (to avoid surprises). If playing, Esc just stops play.  If in paint mode, Esc exits paint mode. Otherwise, if enabled, Esc closes the external pattern editor. In the portfix branch.  Will make it official in version 0.99.10 in a week or two, working on some other issues.

**Comment by mxmilkiib** [comment]
Thank you very much!

**Comment by ahlstromcj** [comment]
Just added this same feature to the external song editor. Same thing: click in piano roll, click Esc to stop playback or to exit Insert mode. Once neither are in force, Esc will close the external window. Fixed in the portfix branch.
