### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by visionm45** [ahlstromcj/seq66#126]
I have tried to build this a few times and i always run into errors. I am running arch linux and so I use yay but this seems to be an upstream issue caused maybe by changes in GCC or liblo. The error I am getting now is

`nsm/nsmbase.cpp: In member function 'void seq66::nsmbase::add_server_method(seq66::nsm::tag, lo_method_handler)': nsm/nsmbase.cpp:885:37: error: cannot convert 'lo_server_thread' {aka 'lo_server_thread_*'} to 'lo_server' {aka 'lo_server_*'} 885 |         (void) lo_server_add_method(m_lo_server_thread, m, p, h, this); |                                     ^~~~~~~~~~~~~~~~~~ |                                     | |                                     lo_server_thread {aka lo_server_thread_*} In file included from /usr/include/lo/lo.h:32, from ../include/nsm/nsmbase.hpp:28, from nsm/nsmbase.cpp:126: `

**Comment by ahlstromcj** [comment]
I got that same error all-of-a-sudden on my Arch Linux box recently. I was surprised to not see the error a long time ago.  I fixed it on March 11 and 12 in the "portfix" branch.

The fix, if you have access to the code, is to comment out the nsmbase member function "add_server_method()" in both nsmbase.hpp and nsmbase.cpp. That function was never used, since Seq66 doesn't provide an NSM server.

I don't know anything about yay (I use pacman). Where is it getting the code from, and which version?  IIRC the AUR package for Seq66 is out-of-date.

**Comment by visionm45** [comment]
so if aur is out of date then the solution is to update aur to the current version since the fix has already been made. Am I understanding this correctly?

**Comment by ahlstromcj** [comment]
That is one solution. Someone else started that AUR, but haven't kept it up.
I will have to figure out how to take it over soon. I am retiring tomorrow and
then will have more time to look into it.

The other solution is to git-clone it, check out the "portfix" branch,
and build it from code as per the INSTALL file.

I've been working on another project, and in a few days will drop that and pick
up again on Seq66.

**Comment by ahlstromcj** [comment]
The fix should now be in version 0.99.13, the master branch.
