### ISSUE TITLE
Play patterns from different sets at the same time ?

### ISSUE THREAD

**Issue by arnaud-jacquemin** [ahlstromcj/seq66#29]
Hi,

Is it possible to play patterns from different sets at the same time ?

When I switch the active set from set 1 to set 2 (via the "Set No." control or the buttons in the "Set Master" window), all armed patterns from set 1 are muted.

I wanted each set to be a different song, and to be able to mix patterns from song N with patterns from song N+1 to 	progressively and seamlessly transition from one song to the other, a bit like in a DJ mix. Is that possible ? How ?

Thanks in advance

**Comment by arnaud-jacquemin** [comment]
I tried with sequence64, and switching from set 1 to set 2 didn't mute the armed patterns in set 1. It looks like there's a regression (or a change of behavior if it's deliberate) between seq66 and sequencer64.

**Comment by ahlstromcj** [comment]
The intent was to follow Seq24, which allows only the current set to be
playing.  So Sequencer64 is doing it wrong.  But nobody's complained so that
will stay as it is.  Which version of Sequencer64 were you using, the Gtkmm or
the Qt version?

I will make what you want as a feature; I already have some commented out code
that let's every set play at once.  But I need to think it through, and also
get re-familiarized with Seq66's set handling.  Thanks for the report!

-------- Arnaud Jacquemin 07:25 Fri 04 Dec      --------

>I tried with sequence64, and switching from set 1 to set 2 didn't mute the armed patterns in set 1. It looks like there's a regression (or a change of behavior if it's deliberate) between seq66 and sequencer64.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/29#issuecomment-738844648

-- 
If God had meant for us to be naked, we would have been born that way.

**Comment by arnaud-jacquemin** [comment]
Hi Chris, thank you for your answer!

I use the Gtkmm version of Sequencer64 0.96.6 (compiled from source last year to jam at [Sonoj](https://www.sonoj.org/2019/)!).
Maybe Sequencer64 is doing it wrong, but I think its behavior is most suitable for seamless "non-stop / techno style" live sets.

It would be a great feature if it could be possible again! Thinking about it, a way to mute all patterns from other sets by request (using a button or midi controller) would be useful too, just in case the performer gets lost.

Thank you for your work on sequencer64 and seq66, it's greatly appreciated!

**Comment by ahlstromcj** [comment]
Provisional support for this is in 0.91.3.  See the new "sets-mode" value in the "[Seq66]" section of the "qse66.rc" file.
