### ISSUE TITLE
Song editor scrolling?

### ISSUE THREAD

**Issue by mxmilkiib** [ahlstromcj/seq66#37]
The ability to use the mousewheel to scroll up and down (and, with shift held down, left and right) would be handy. Thanks for all your work! :)

**Comment by ahlstromcj** [comment]
Using the mouse wheel is a bit tricky, as there is an internal "qscrollmaster"
object that coordinates the scrolling of the locked panes in both the song and
pattern editors.  There's another request for that in the pattern editor, but
the pattern editor is an even trickier case.  I put both on the TODO list.
Thanks!

-------- Milkii Brewster 18:08 Sat 09 Jan      --------

>The ability to use the mousewheel to scroll up and down (and, with shift held down, left and right) would be handy. Thanks for all your work! :)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/seq66/issues/37

-- 
Do not overtax your powers.

**Comment by ahlstromcj** [comment]
For now, we have mitigated this issue by enabling the scroll wheel in the pattern and song piano rolls, and disabled it in qseqdata, qseqtime, qstriggereditor, qperfnames, and qpertime.

This fix is in the portfix branch and will be merged into master for version 0.99.4.  Since this is a long overdue follow-on to issue #3, I'll close this one here and leave #3 open.
