### ISSUE TITLE
MIDI Controls not responding

### ISSUE THREAD

**Issue by Tarsassum** [ahlstromcj/seq66#72]
I've been trying for a while to get Seq66 to work with my Novation LaunchKey 25 keyboard but I can't seem to get Seq66 to respond to anything as a midi-control, no matter what I seem to do.

The keyboard has two busses and the drumpads and pots can be switched to the second bus. I'm trying to use the pads (2x8 square pads with two round buttons, in bus2, channel 1 ranged 96-120) as a controller and use the actual keyboard as the 'instrument'/note input.

~~~
[loop-control]

 0 "1"            [ 0 0x90   96   1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 0
 1 "q"            [ 0 0x90   97   1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 1
 2 "a"            [ 0 0x90   98   1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 2
 3 "z"            [ 0 0x90   99   1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 3
 4 "2"            [ 0 0x90   100  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 4
 5 "w"            [ 0 0x90   101  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 5
 6 "s"            [ 0 0x90   102  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 6
 7 "x"            [ 0 0x90   103  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 7
 8 "3"            [ 0 0x90   112  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 8
 9 "e"            [ 0 0x90   113  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 9
10 "d"            [ 0 0x90   114  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 10
11 "c"            [ 0 0x90   115  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 11
12 "4"            [ 0 0x90   116  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 12
13 "r"            [ 0 0x90   117  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 13
14 "f"            [ 0 0x90   118  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 14
15 "v"            [ 0 0x90   119  1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 15`
~~~

I can record notes, midi-thru works so I know seq66 is getting my input. Keyboard input works as well but I get no response to the pads other than when I midi-thru/rec a loop. Even in the terminal with --verbose it gives no indication it's even receiving anything. I even tried changing control-buss from 0xFF to 0x02 to no avail.

I'm very grateful for you putting in the time to rescue this amazing piece of software, imho the live looping approach to sequencing is the most intuitive way to make music and it's heartwarming to see you giving it the attention it deserves.

**Comment by ahlstromcj** [comment]
I am going to study the Launchkey manual(s) to see if there are any tricks
to it not covered by the current MIDI control setup in Seq66.

In the meantime.... Make sure the qseq66.rc file has:

[midi-control-file]

active = true
name = "qseq66-lp-mini.ctrl"

(Using the actual name of your ctrl file).

In the 'rc' file's "[midi-input]" section, make sure the pad-controller's port
is enabled.  You can check the settings in Edit / Preferences / MIDI Input.

Then make sure your 'ctrl' file has:

[midi-control-settings]

load-key-controls = true
load-midi-controls = true
control-buss = 2 (or whatever shows up in "aplaymidi -l" or "jack_lsp")
midi-enabled = true

To tell you the truth, I have to monkey around to get a new setup to work.
Bad entries can de-activate the 'ctrl' file and I have to reactivate it
in the 'rc' file. Getting it all lined up is still a bit problematic. :-(

Thanks for the kudos on reviving Seq24... I liked it because it wasn't a
gigantic piece of software and was slick to use. But it had a fair number of
bugs and I had some equipment issues I wanted to work around.  Then I got to
feeling my version (Sequencer64) was itself getting a bit too bloaty, and I also
wanted to use the efficiencies of C++-11 and above.  One of these days I hope to
do nothing but make music with this app :-).

-------- Tarsassum 09:19 Sun 28 Nov      --------

>I've been trying for a while to get Seq66 to work with my Novation LaunchKey 25 keyboard but I can't seem to get Seq66 to respond to anything as a midi-control, no matter what I seem to do.
>
>~~~
>[loop-control]
>
> 0 "1"            [ 0 0x90   96   1   127 ][ 0 0x00   0   0   0 ] [ 0 0x00   0   0   0 ] # Loop 0

-- 
Your domestic life may be harmonious.

**Comment by ahlstromcj** [comment]
I checked ALSA and got it working both ends (I/O).  Then I started Qjackctl (with startup scripts to control JACK in the presence of PulseAudio). One can see in the ALSA tab the clients... Midi Through at port 0 (the first entry) and so on.  Edit the 'ctrl' file as above to match, and enable the appropriate port, which unfortunately shows up with a generic name in Seq66.

If you stop Seq66 and run "a2jmidid  --export-hw" the USB MIDI devices then show up in the MIDI tab as well as the ALSA tab, but in the MIDI tab they are subs of the "a2j" devices.  You can enable those devices in Seq66, close it, edit the 'ctrl' to match the a2j device index number, and run Seq66 and it should still work.

The mystery I am see on Ubuntu 20 is the the original "system" devices still show up after running aj2midid, which is something I don't recall before.

All this port numbering is a PITA.  A port mapping feature is in place; I will eventually enable the 'ctrl' file to use port name lookup.  See "Port Mapping" in the user manual.  Still some work to do (as usual).
