### ISSUE TITLE
Target for building both qseq66 and seq66cli in a single step

### ISSUE THREAD

**Issue by fpesari** [ahlstromcj/seq66#84]
Hello,

I am a packager from the GeekosDAW project and I made the [openSUSE package](https://software.opensuse.org/package/seq66) for seq66. 

I wanted to ask you if you could please provide a target to build and install both qseq66 and seq66cli in a single step.

**Comment by ahlstromcj** [comment]
I'm thinking about how to do this.  The sticking point is that there are a few
macros (e.g. APP_NAME --> SEQ66_APP_NAME) that are different between builds.
The easy way (have a short script to reconfigure and build both) requires
building the same libraries twice, I think, so that's a no-good.  Do you have
any idea, or know of other projects that do that?  Will keep thinking on this.
One other idea is a hard-wired seq66-config.h, like I use for the qmake builds.
(See the include/qt directory).

-------- Fabio Pesari 23:21 Mon 09 May      --------

>Hello,
>
>I am a packager from the GeekosDAW project and I made the [openSUSE package](https://software.opensuse.org/package/seq66) for seq66.
>
>I wanted to ask you if you could please provide a target to build and install both qseq66 and seq66cli in a single step.

**Comment by fpesari** [comment]
Other projects are structured differently, so it would be hard to pinpoint a single shared solution.

Some might have a couple of different build targets and the `all` target depends on them, but this says nothing about the internal structure.

I think one idea could be to move the common stuff to a separate target (let's call it `base`) and have all binary targets depend on that `base` target. This, at least, could avoid the rebuilding of libs in common between the targets.

I am not any good at Automake, I barely can deal with it a packager :laughing: but at least in CMake I suspect that something like [add_compile_definitions](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions) could be used to implement a solution to your problem - simply set different preprocessor definitions in each target. There must be an equivalent in Automake.

**Comment by fpesari** [comment]
A bit OT (and I don't think that this issue is attributable to Automake) but I also would add that if you are willing to put a bit of time into CMake, it would make a great time investment because:
1) AFAIK and IMHO, it has gotten really good lately
2) [Qt6 switched to CMake](https://www.qt.io/blog/qt-6-build-system), so since you use Qt this might be another point in favor of it
3) (my own estimate) There is a much larger pool of developers using CMake than Automake. This means more potential contributors and more resources for contributors.

Automake was very seminal and even as a GNU fan, I must say that it's very hard to get into it compared to CMake, premake or meson.

(not opening a separate issue for this because it's your free choice as the author, just wanted to share my thoughts since build systems were mentioned)

**Comment by ahlstromcj** [comment]
When I first saw cmake, I vomited a little in my throat, and I still cannot get
over naming a make file with a "txt" extension.  I saw that Qt is moving to it,
though not sure why because qmake is pretty easy to use.

Automake has its issues, but I've been using it a long time and solve most
problems pretty quickly.  Perhaps you'd like to make a cmake setup?  :-)

Anyway, I had added run-time settings for app name, client name, etc. in order
to better support session management, and I was able to leverage that so that
seq66cli overrides macros like SEQ66_APP_NAME, and it is clearly seen in the
qjackctl connections graph.

If you want, you can checkout the "portfix" branch, do a full-clean, and follow
the simple process at line 91 of the INSTALL file.  If you have any issues or
recommendations, let me know.  And thanks for kicking my ass into gear re this
build issue :-D

**Comment by ahlstromcj** [comment]
If I evern do a Seq66 version 2, I will likely do 3 things:  Split out the MIDI
and utility code into separate libraries, use Qt 6, and use cmake.  Reading
through tutorials on it now.  Won't change to cmake for the current version,
way too much work.  I did just refactor the bootstrap to fix a couple bugs
including fixing out-of-source builds; it is in the portfix branch.  Probably
will create version 0.98.8 master sooner than I'd usually do.  Thanks!

-- 
There is a fly on your nose.

**Comment by mxmilkiib** [comment]
Meson is what a number #lad devs have moved to in recent years.

**Comment by eli-schwartz** [comment]
> I'm thinking about how to do this. The sticking point is that there are a few macros (e.g. APP_NAME --> SEQ66_APP_NAME) that are different between builds. The easy way (have a short script to reconfigure and build both) requires building the same libraries twice, I think, so that's a no-good. Do you have any idea, or know of other projects that do that?

In general, any build system should allow you to define multiple targets with different names, but each one uses the same source files compiled with different build flags. This generally works out of the box (at least I know it does in autotools and meson) because object files get scoped according to the targets they are part of.

**Comment by ahlstromcj** [comment]
I finally got the dual build stuff into master, for version 0.98.8.

I also saw some random request on the web, mentioned by @mxmilkiib about having access to a tutorial.  So I added an HTML tutorial, and added Help menu entries for the tutorial and the user manual.  Have only tested in on Linux so far, and there are a few things I need to do to improve the navigation.  Any suggestions for additional content are welcome, as long as they don't amount to "redo the PDF manual in HTML" :-D

**Comment by ahlstromcj** [comment]
Unfortunately, there's a nasty bug in the current code :-( See issue #85.  I
have a fix, but a little more testing and tweaking to do; version 0.98.9 will
be out a lot sooner than I planned.

-------- Fabio Pesari 04:04 Tue 24 May      --------

>Awesome! Updated the package in the openSUSE repo, now containing both binaries. Thank you!

**Comment by ahlstromcj** [comment]
Okay, version 0.98.9 should be working now, tagged and in master branch.  (Thunks head with palm).

**Comment by ahlstromcj** [comment]
Closing this one.  I've been using meson for a complete rewrite of Scavone's RtMidi project, and it seems better than cmake to me, although it can use cmake functions as well.
