### ISSUE TITLE
The mousewheel doesn't works to scroll or zoom in Editor.

### ISSUE THREAD

**Issue by arumihsnek** [ahlstromcj/seq66#86]
I can't scroll or zoom in the Editor or Song tabs. The laptop touch pad doesn't works neither.
 But it works for adjust the tempo or in the scroll bar, but not in the piano roll.
 I'm forgetting something?

**Comment by ahlstromcj** [comment]
See issue #37.  I had to link the time scrollbar and the piano keys scrollbar to the main piano roll scrollbar.  If I allow mouse scrolling to work, then scrolling in the piano roll works (it is the "scroll master") and scrolls the time and keys panes.  However, scrolling in those panes does not move the piano roll.

I've been lazy about this issue, but perhaps at some point I can work out a way to feed the scrolling from the time or keys pane back to the piano roll.  I will think about this at some point.

If you click in the piano roll, you can use the arrow keys to move around.  Also page up, page down, ctrl-home, ctrl-end.  (Not sure why I required the control key for the latter.)

**Comment by ahlstromcj** [comment]
For now, we have mitigated this issue by enabling the scroll wheel in the pattern and song piano rolls, and disabled it in qseqdata, qseqtime, qstriggereditor, qperfnames, and qpertime.

This fix is in the portfix branch and will be merged into master for version 0.99.4.  Since this is a long overdue follow-on to issue #3, I'll close this one here and leave #3 open.

I haven't yet tackled the zooming issue, but there are buttons and keystrokes to do that.
